# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P4ZG2gN4K24ph9ymwUlzMMN3g5s3LMrh
"""

import os
from flask import Flask, request, jsonify, send_from_directory
import functions

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
app = Flask(__name__)

UPLOAD_FOLDER = 'static/uploads'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

@app.route("/processImage", methods=['POST'])
def process_image():
    if 'imageFile' not in request.files:
        return jsonify({"error": "No image file found"}), 400

    image = request.files['imageFile']
    img_path = os.path.join(UPLOAD_FOLDER, image.filename)
    image.save(img_path)

    label, bbox, confidence, output_path = functions.yolo(img_path)

    try:
        os.remove(img_path)
    except Exception as e:
        print(f"Error removing file: {e}")

    output_image_path = os.path.basename(output_path)

    return jsonify({
        "label": label,
        "bbox": bbox,
        "confidence": confidence,
        "output_image_path": output_image_path
    })

@app.route("/uploads/<filename>")
def uploaded_file(filename):
    return send_from_directory(UPLOAD_FOLDER, filename)

if __name__ == '__main__':
    app.run(debug=True)
